//============================================================================
// Name        : main.c
// Author      : Christopher Ley
// Version     : 1.0
// Project	   : leylogd_x86
// Created     : 24/02/15
// Modified    : 27/02/15
// Copyright   : Do not modify without express permission from the author
// Description : main file for [leylogd_x86] daemon process x86 variant
// Notes	   : useful signals:
//					- SIGALRM; generated by setitimer() & alarm()
//					- SIGUP; when hamg up occurs
//					- SIGTERM; standard stop signal sent by killall etc
//						should be used before SIGKILL
//					- SIGINT; from a user interrupt
//					- SIGKILL; always kills the service
//					- SIGPWR; if battery is low a daemon can send SIGPWR
//							to init
//============================================================================
#include <stdlib.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <time.h>
#include <signal.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include "become_daemon.h"

/**************************** LOGGING FUNCTIONS  ****************************/
/****** Static File Pointers ******/
static FILE *logfp;		/* Log file stream */
static const char *LOG_FILE = "/var/log/leyld.log";
static const char *CONFIG_FILE = "/etc/leylogd/leyld.conf";

/****** Message Loggers ******/
/* Log Message */
static void logMessage(const char *format,...)
{
	va_list argList;
	const char *TIMESTAMP_FMT = "%F %X";	/* = YYYY-MM-DD HH:MM:SS */
#define TS_BUF_SIZE sizeof("YYYY-MM-DD HH:MM:SS")	/* Includes '\0' */
	char timestamp[TS_BUF_SIZE];
	time_t t;
	struct tm *loc;

	t = time(NULL);
	loc = localtime(&t);
	if (loc == NULL || strftime(timestamp, TS_BUF_SIZE, TIMESTAMP_FMT, loc) == 0)
		fprintf(logfp, "??Unknown time??: ");
	else
		fprintf(logfp, "%s: ", timestamp);

	va_start(argList, format); /* stdarg.h macro */
	vfprintf(logfp, format, argList);
	fprintf(logfp, "\n");
	va_end(argList);
}
/* Open Log file */
static void logOpen(const char *logFilename)
{
	mode_t m; /*mode of file*/

	m = umask(077); /* File mode creation mask */
	logfp = fopen(logFilename, "a");
	umask(m);

	if(logfp == NULL)
		exit(EXIT_FAILURE);
	setbuf(logfp, NULL); /* Disable stdio buffering */

	logMessage("Opened log file");
}
/* Close Log file */
static void logClose(void)
{
	logMessage("Closing log file");
	fclose(logfp);
}
static void readConfigFile(const char *configFilename)
{
	FILE *configfp;
#define SBUF_SIZE 100
	char str[SBUF_SIZE];

	configfp = fopen(configFilename, "r");
	if(configfp != NULL) {	/* Ignore nonexistent file */
		if (fgets(str, SBUF_SIZE, configfp) == NULL)
			str[0] = '\0';
		else
			str[strlen(str) - 1] = '\0';	/* Strip tailing */
		logMessage("Read config file: %s", str);
		fclose(configfp);
	}
}
/****************************************************************************/

/**************************** INTERRUPT HANDLERS ****************************/
/****** Atomic interrupt flags ******/
/* Set nonzero on receipt of interrupt,set as volatile so that the compiler
 * dosen't store as a register value and helps with re-entrancy issues, the
 * atomic identifier ensures the global flag is atomic,i.e. can be changed
 * in one clock cycle! */
static volatile sig_atomic_t termReceived = 0;
static volatile sig_atomic_t alrmReceived = 0;
static volatile sig_atomic_t hupReceived = 0;

/****** Interrupt Handler Function ******/
static void interruptHandler(int sig)
{
    /* A Quick interrupt handler to try to avoid re-entrancy */
    switch(sig)
    {
        case SIGHUP:
            hupReceived = 1;
            break;
        case SIGINT:
        case SIGTERM:
            termReceived = 1;
            break;
        case SIGALRM:
            alrmReceived = 1;
            break;
    }
}
/****************************************************************************/

/**************************** MAIN ****************************/
int main(int argc, char *argv[])
{
	/* Set up interrupt handler */
	struct sigaction act; // defined by signal.h
	sigemptyset(&act.sa_mask);
	act.sa_flags = 0;
	act.sa_handler = interruptHandler;
	/* signals to handle */
	sigaction(SIGHUP, &act, NULL); // catch hangup signal
	sigaction(SIGTERM, &act, NULL); // catch terminate (--stop|stop) signal
	sigaction(SIGINT, &act, NULL); // catch Ctrl=C signal
	sigaction(SIGALRM, &act, NULL);// catch timer alarm

	if(becomeDaemon(0) == -1){
		logMessage("Daemonise Failure");
		exit(EXIT_FAILURE);
	}
	/* Open Log file */
	logOpen(LOG_FILE);
	logMessage("Successfully Daemonised");
	readConfigFile(CONFIG_FILE);
	int count;
	if (argc > 1){
		for(count = 1; count < argc; count++){
			 logMessage(argv[count]);
		}
	}

	/* Set up Timer */
	struct itimerval itv;
	/* Set timer values*/
	 itv.it_value.tv_sec = 30;
	 itv.it_value.tv_usec = 0;
	 itv.it_interval.tv_sec = 30;
	 itv.it_interval.tv_usec = 0;

	if (setitimer(ITIMER_REAL, &itv, 0) == -1){
			logMessage("Timer Failure");
			exit(EXIT_FAILURE);
		 }
	logMessage("Timer Successfully started");

	for(;;){ /*ever*/
		if(termReceived != 0){
			//TODO close file pointer for logging
			termReceived = 0;
			logClose();
			exit(EXIT_SUCCESS);
		}else if(alrmReceived != 0){
			logMessage("Logging Data");
			alrmReceived = 0;
			//TODO Data logging
		}else if(hupReceived != 0){
			logMessage("Hangup Recieved");
			readConfigFile(CONFIG_FILE);
			hupReceived = 0;
			//TODO Re-initialise parameters
		}else{
			pause(); /* suspend until a signal is received.*/
			logMessage("Unpaused");
		}
	}
	exit(EXIT_SUCCESS);
}
